---
- name: Add an Apt signing key influxdb
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- apt_repository:
    repo: deb https://repos.influxdata.com/debian stretch stable
    state: present
    mode: 600

- name: Update apt-get cache
  apt: >
    update_cache=yes
    cache_valid_time=360

- name: Update all packages to the latest version
  apt: >
    upgrade=yes

- name: install influxdb
  apt:
    name: influxdb
    state: present

- name: Make sure influxdb is running
  systemd:
    enabled: yes
    state: started
    name: influxdb

- name: Ensure weather directory exists
  file:
    path: "/var/var/influxdb/scripts"
    recurse: yes
    state: directory
    owner: pi
    group: pi

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: "/var/var/influxdb/scripts/{{ item }}"
    owner: pi
    group: pi
    mode: 0775
  with_items:
    - config.ini
    - create_db.py

- name: execute create_db.py script
  script:
    cmd: "/var/var/influxdb/scripts/create_db.py"
    chdir: "/var/var/influxdb/scripts"