---
- name: Ensure ginlong directory exists
  file:
    path: "/var/ginlong/"
    state: directory
    owner: pi
    group: pi
    
- name: Ensure ginlong directory exists
  file:
    path: "/var/log/ginlong"
    state: directory
    owner: pi
    group: pi

- name: Copy ginlong.scraper.py with owner and permissions
  copy:
    src: ginlong.scraper.py
    dest: /var/ginlong/ginlong.scraper.py
    mode: '0766'

- name: template ginlong.scraper.service with owner and permissions
  template:
    src: ginlong.scraper.service.j2
    dest: /lib/systemd/system/ginlong.scraper.service
    mode: '0644'

- name: install pip packages
  pip:
    name: [ "requests", "influxdb" ]
  become: true

- name: Make sure ginlong.scraper is running
  systemd:
    enabled: yes
    state: started
    name: ginlong.scraper

- name: restart service ginlong.scraper"
  cron:
    name: "restart service ginlong.scraper"
    minute: "0,15,30,45"
    job: "service ginlong.scraper restart"
    user: root

- name: include create continuous queries 
  include_tasks: init_measurements.yml     