---
- name: Ensure grafana key directory exists
  become: false
  file:
    path: "{{ grafana_api_keys_dir }}/{{ inventory_hostname }}"
    state: directory
  delegate_to: localhost

- set_fact:
    pi_password: "{{lookup('file', '{{ pswrdfile }}') }}"

- set_fact:
    pi_passwrd: "{{ pi_password | password_hash('sha512' ) }}"

- name: Change Password
  uri:
    url: "{{ grafana_api_url }}/api/user/password"
    user: "{{ grafana_security.admin_user }}"
    oldPassword: "{{ grafana_security.admin_password }}"
    newPassword: "{{ pi_passwrd }}"
    force_basic_auth: true
    return_content: true
  no_log: true
  ignore_errors: yes

- name: Check api key list
  uri:
    url: "{{ grafana_api_url }}/api/auth/keys"
    user: "{{ grafana_security.admin_user }}"
    password: "{{ pi_passwrd }}"
    force_basic_auth: true
    return_content: true
  no_log: true
  register: existing_api_keys

- name: Create grafana api keys
  uri:
    url: "{{ grafana_api_url }}/api/auth/keys"
    user: "{{ grafana_security.admin_user }}"
    password: "{{ pi_passwrd }}"
    force_basic_auth: true
    method: POST
    body_format: json
    body: "{{ item | to_json }}"
  with_items: "{{ grafana_api_keys }}"
  no_log: true
  when: ((existing_api_keys['json'] | selectattr("name", "equalto", item['name'])) | list) | length == 0
  register: new_api_keys

- name: Create api keys file to allow the keys to be seen and used by other automation
  become: false
  copy:
    dest: "{{ grafana_api_keys_dir }}/{{ inventory_hostname }}/{{ item['item']['name'] }}.key"
    content: "{{ item['json']['key'] }}"
    backup: false
  when: item['json'] is defined
  with_items: "{{ new_api_keys['results'] }}"
  delegate_to: localhost