---
- name: Download grafana
  get_url: 
    url: "https://github.com/fg2it/grafana-on-raspberry/releases/download/v5.1.4/grafana_5.1.4_armhf.deb"
    dest: "/home/pi/grafana_5.1.4_armhf.deb"
    timeout: 600

- name: Install grafana_5.1.4_armhf.deb
  apt: 
    deb: "/home/pi/grafana_5.1.4_armhf.deb"
    state: present
  become: 
    yes

- name: install plugin fetzerch-sunandmoon-datasource
  shell: |
    grafana-cli plugins install fetzerch-sunandmoon-datasource

- name: Restart grafana before configuring datasources and dashboards
  meta: flush_handlers
  
- include: api_keys.yml
- include: datasources.yml
- include: plugins.yml
- include: dashboards.yml

- name: Make sure grafana-server is running
  systemd:
    enabled: yes
    state: started
    name: grafana-server
