---
- name: Import grafana plugin
  become: true
  unarchive:
    src: "{{ item }}"
    dest: "{{ grafana_data_dir }}/plugins{{ item | basename }}"
    mode: 0640
  with_fileglob:
    - "{{ grafana_dashboards_dir }}/*.zip"
  register: _plugins_copied

- name: Check which plugins are installed
  find:
    file_type: directory
    recurse: false
    paths: "{{ grafana_data_dir }}/plugins"
  register: installed_plugins

- name: Install plugins
  become: true
  command: "grafana-cli --pluginsDir {{ grafana_data_dir }}/plugins plugins install {{ item }}"
  args:
    creates: "{{ grafana_data_dir }}/plugins/{{ item }}"
  with_items: "{{ grafana_plugins | difference(installed_plugins.files) }}"
  register: _plugin_install
  until: _plugin_install is succeeded
  retries: 5
  delay: 2
  notify:
    - restart grafana