---
- name: Import grafana plugins 1
  unarchive:
    src: "{{ item }}"
    dest: "{{ grafana_data_dir }}/plugins/"
    mode: 0755
    owner: grafana
    group: grafana
  with_fileglob:
    - "{{ plugin_dashboards_dir }}/*.zip"

- name: Manually install plugins
  command: "grafana-cli --pluginsDir {{ grafana_data_dir }}/plugins plugins install {{ (( item | basename | splitext)[:-1] | join('.')) }}"
  with_fileglob:
    - "{{ plugin_dashboards_dir }}/*.zip"
  notify:
    - restart grafana

- name: Check which plugins are installed
  find:
    file_type: directory
    recurse: false
    paths: "{{ grafana_data_dir }}/plugins"
  register: installed_plugins

- name: Install plugins
  become: true
  command: "grafana-cli --pluginsDir {{ grafana_data_dir }}/plugins plugins install {{ item }}"
  args:
    creates: "{{ grafana_data_dir }}/plugins/{{ item }}"
  with_items: "{{ grafana_plugins | difference(installed_plugins.files) }}"
  register: _plugin_install
  until: _plugin_install is succeeded
  retries: 5
  delay: 2
  notify:
    - restart grafana