---
- set_fact:
    pi_password: "{{lookup('file', '{{ pswrdfile }}') }}"

- name: Add pi user
  uri:
    url: "{{ grafana_api_url }}/api/admin/users"
    user: "{{ grafana_security.admin_user }}"
    password: "{{ grafana_security.admin_password }}"
    force_basic_auth: true
    return_content: true
    method: POST
    body_format: json
    body:
      name: "pi"
      email: "no@body.com"
      login: "pi"
      password: "{{ pi_password }}"
      isGrafanaAdmin: true
#  no_log: true
  ignore_errors: yes
  register: pi_user

- debug:
    msg: "{{ pi_user }}"

- name: Add ansible user
  uri:
    url: "{{ grafana_api_url }}/api/admin/users"
    user: "{{ grafana_security.admin_user }}"
    password: "{{ grafana_security.admin_password }}"
    force_basic_auth: true
    return_content: true
    method: POST
    body_format: json
    body:
      name: "pi"
      email: "no@body.com"
      login: "{{ grafana_security.ansible_user }}"
      password: "{{ grafana_security.ansible_password }}"
      isGrafanaAdmin: true
#  no_log: true
  ignore_errors: yes  
  register: ansible_user