---
- hosts: rpi
  become_user: root
  become: yes

  roles:
  - role: local
  - role: nginx
  - role: influxdb
  - role: p1
  - role: solar
  - role: node-exporter
  - role: openweathermap
  - role: prometheus
  - role: grafana
  