---
- hosts: localhost
  roles:
  - role: influxdb
    become_user: root
    become: yes
  - role: p1
    become_user: root
    become: yes
  - role: solar
    become_user: root
    become: yes
  - role: node-exporter
    become_user: root
    become: yes
  - role: prometheus
    become_user: root
    become: yes    
  - role: grafana
    become_user: root
    become: yes
  