---
- hosts: localhost
  roles:
  - role: influxdb
    become_user: root
    become: yes
  - role: p1
    become_user: root
    become: yes
  - role: ginlong
    become_user: root
    become: yes
  - role: grafana
    become_user: root
    become: yes
  