---

- name: Install required packages
  package:
    name: [ 'unzip', ''man-db' ]
    state: present
  become: true  

- name: Create temporary working directory
  file:
    path: "{{ rclone_setup_tmp_dir }}"
    state: directory
    mode: '0775'

- name: Do stable install
  include_tasks: stable.yml  

- name: Copy rclone binary
  copy:
    src: "{{ rclone_setup_tmp_dir }}/rclone-v{{ rclone_version }}-linux-arm/rclone"
    dest: "/usr/local/bin/rclone"
    mode: '0755'
    owner: root
    group: root
    remote_src: true
  become: true

- name: Create config directory
  file:
    path: '{{ rclone_config_location | dirname }}'
    state: directory
    mode: '0700'
  when: rclone_configs is defined

- name: Set up rclone config
  template:
    src: rclone.conf.j2
    dest: '{{ rclone_config_location }}'
  when: rclone_configs is defined

