{
 "title": "Solar Copy",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Power Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "power_consumption" }
     ]
    }
   ]
  },
  {
   "title": "Daily Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "Daily_Generation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today vs Yesterday",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "Daily_Generation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Update from Inverter",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "updateDate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Temparature",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "Inverter_Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "power_consumption" }
     ]
    }
   ]
  },
  {
   "title": "Last Month Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "Generation_Last_Month" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peak power generation",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 3 },
   "targets": [
    {
     "alias": "Peak Power",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "AC_Power" ], "type": "field" },
       { "params": [ "1" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Best Days",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 3 },
   "targets": [
    {
     "alias": "Generated",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "Daily_Generation" ], "type": "field" },
       { "params": [ "1" ], "type": "top" }
      ]
     ]
    },
    {
     "alias": "Efficiency",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "Daily_Generation" ], "type": "field" },
       { "params": [ "1" ], "type": "top" },
       { "params": [ "/ 5.22" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter AC Voltage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "AC_Voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "Total_Generation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter AC Frequency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "AC_Frequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exporting to Net",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "power_production" }
     ]
    }
   ]
  },
  {
   "title": "Solar PV",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "AC_Power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Usage from Net",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "$tag_entity_id",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "power_consumption_low" },
      { "condition": "OR", "key": "entity_id", "operator": "=", "value": "power_consumption_normal" }
     ]
    }
   ]
  },
  {
   "title": "Power Return to Net",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "power_production" }
     ]
    }
   ]
  },
  {
   "title": "PV Generated Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "AC_Power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "DC1",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "DC_Current1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DC2",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "DC_Current2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Return to Net",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "$tag_entity_id",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "power_production_low" },
      { "condition": "OR", "key": "entity_id", "operator": "=", "value": "power_production_normal" }
     ]
    }
   ]
  },
  {
   "title": "Generated per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Day",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "Daily_Generation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "DC Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "DC1",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "DC_Voltage_PV1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DC2",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "DC_Voltage_PV2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "AC Voltage",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "AC_Voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "AC Current",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "AC_Current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "hz" }
   ],
   "targets": [
    {
     "alias": "AC Frequency",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "AC_Frequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sun Altitude",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "sun_altitude"
    }
   ]
  },
  {
   "title": "Temparature Inverter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 39 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "Inverter_Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar radiation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 39 },
   "yaxes": [
    { "format": "Wm2" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "W/m2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}