- name: Ensure influxdb directory exists
  file:
    path: "/var/influxdb/scripts"
    recurse: yes
    state: directory
    owner: pi
    group: pi

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: "/var/influxdb/scripts/{{ item }}"
    owner: pi
    group: pi
    mode: 0775
  with_items:
    - weather_config.ini
    - weather_init_measurements.py
   
- name: execute weather_init_measurements.yml.py script Weather
  command:
    cmd: "python /var/influxdb/scripts/weather_init_measurements.py"
  args:
    chdir: "/var/influxdb/scripts"