---
- name: include apikey
  include_vars: "openweathermap.yaml"

- name: install pip packages
  pip:
    name: [ "requests", "influxdb", "pyowm" ]

- name: Ensure weather directory exists
  file:
    path: "/var/weather/"
    state: directory
    owner: pi
    group: pi

- name: Ensure weather directory exists
  file:
    path: "/var/log/weather"
    state: directory
    owner: pi
    group: pi

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: "/var/weather/{{ item }}"
    owner: pi
    group: pi
    mode: 0775
  with_items:
    - weather-logger.py

- name: template config.ini with owner and permissions
  template:
    src: weather_config.ini.j2
    dest: "/var/weather/weather_config.ini"
    owner: pi
    group: pi
    mode: '0644'

- name: weather-logger.service with owner and permissions
  copy:
    src: weather-logger.service
    dest: /lib/systemd/system/weather-logger.service
    mode: '0644'

- name: Make sure weather.listen is running
  systemd:
    enabled: yes
    state: started
    daemon_reload: true
    name: weather-logger

- name: restart service weather-logger "
  cron:
    name: "restart service weather-logger "
    minute: "*/15"
    job: "/usr/sbin/service weather-logger  restart"
    user: root

- name: include create continuous queries 
  include_tasks: init_measurements.yml     