- name: Update apt-get cache
  apt: >
    update_cache=yes
    cache_valid_time=360

- name: Update all packages to the latest version
  apt: > 
    upgrade=yes

- name: set timezone to Europe/Amsterdam
  timezone:
    name: Europe/Amsterdam
    
- name: Remove not used applications
  apt: 
    name: [ "wolfram-engine", "libreoffice*", "oracle-java*", "scratch2", "scratch" ]
    state: absent
  
    