{
 "title": "Raspberry metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Used memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total memory" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used memory"
    }
   ]
  },
  {
   "title": "Free swap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_SwapFree_bytes", "legendFormat": "Free" }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Used disk",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/root\"} - node_filesystem_avail_bytes{device=\"/dev/root\"}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/root\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/root\"} - node_filesystem_avail_bytes{device=\"/dev/root\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Cpu load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load" }
   ]
  },
  {
   "title": "Number of TCP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_netstat_Tcp_CurrEstab", "legendFormat": "Count" }
   ]
  }
 ]
}