{
 "title": "verbruik",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "P1 Smartmeter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Kwh" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "+P1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+P1" ], "type": "alias" }
      ],
      [
       { "params": [ "+P2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+p2" ], "type": "alias" }
      ],
      [
       { "params": [ "+P3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+P3" ], "type": "alias" }
      ],
      [
       { "params": [ "-P1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" },
       { "params": [ "-P1" ], "type": "alias" }
      ],
      [
       { "params": [ "-P2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" },
       { "params": [ "-P2" ], "type": "alias" }
      ],
      [
       { "params": [ "-P3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" },
       { "params": [ "-P3" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current R",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ginlong",
     "select": [
      [
       { "params": [ "AC_Current_R/U/A_[A]" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "R" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current S",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ginlong",
     "select": [
      [
       { "params": [ "AC_Current_S/V/B_[A]" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "S" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current T",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ginlong",
     "select": [
      [
       { "params": [ "AC_Current_T/W/C_[A]" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "T" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage R",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ginlong",
     "select": [
      [
       { "params": [ "AC_Voltage_R/U/A_[V]" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "R" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage S",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ginlong",
     "select": [
      [
       { "params": [ "AC_Voltage_S/V/B_[V]" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "S" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage S",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ginlong",
     "select": [
      [
       { "params": [ "AC_Voltage_T/W/C_[V]" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "S" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ginlong",
     "select": [
      [
       { "params": [ "DC_Power_PV1_[kW]" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "PV1" ], "type": "alias" }
      ],
      [
       { "params": [ "DC_Power_PV2_[kW]" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "PV2" ], "type": "alias" }
      ],
      [
       { "params": [ "DC_Voltage_PV3_[V]" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "PV3" ], "type": "alias" }
      ],
      [
       { "params": [ "DC_Power_PV4_[W]" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "PV4" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Generation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "volt", "label": "Voltage" }
   ],
   "targets": [
    {
     "alias": "Voltage $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ginlong",
     "query": "SELECT integral(\"AC_Voltage_R/U/A_[V]\") AS \"R\", integral(\"AC_Voltage_S/V/B_[V]\") AS \"S\", integral(\"AC_Voltage_T/W/C_[V]\") AS \"T\" FROM \"ginlong\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AC_Voltage_R/U/A_[V]" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "R" ], "type": "alias" }
      ],
      [
       { "params": [ "AC_Voltage_S/V/B_[V]" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "S" ], "type": "alias" }
      ],
      [
       { "params": [ "AC_Voltage_T/W/C_[V]" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "T" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Current $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ginlong",
     "select": [
      [
       { "params": [ "AC_Current_R/U/A_[A]" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "R" ], "type": "alias" }
      ],
      [
       { "params": [ "AC_Current_S/V/B_[A]" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "S" ], "type": "alias" }
      ],
      [
       { "params": [ "AC_Current_T/W/C_[A]" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "T" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}