---
packages:
  - {url: "http://ftp.us.debian.org/debian/pool/main/i/influxdb/influxdb_1.0.2+dfsg1-1_armhf.deb", name: "influxdb_1.0.2+dfsg1-1_armhf" }
  - {url: "http://ftp.us.debian.org/debian/pool/main/i/influxdb/influxdb_1.0.2+dfsg1-1_armhf.deb", name: "influxdb_1.0.2+dfsg1-1_armhf" }
  - {url: "http://ftp.us.debian.org/debian/pool/main/g/grafana/grafana-data_2.6.0+dfsg-3_all.deb", name: "grafana-data_2.6.0+dfsg-3_all" }
  - {url: "http://ftp.us.debian.org/debian/pool/main/g/grafana/grafana_2.6.0+dfsg-3_armhf.deb", name: "grafana_2.6.0+dfsg-3_armhf" }