- name: Ensure influxdb directory exists
  file:
    path: "/var/influxdb/scripts"
    recurse: yes
    state: directory
    owner: pi
    group: pi

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: "/var/influxdb/scripts/{{ item }}"
    owner: pi
    group: pi
    mode: 0775
  with_items:
    - solar_config.ini
    - solar_init_measurements.py
    - rs485_config.ini
    - rs485_init_measurements.py
   
- name: execute solar_init_measurements.py script Solar
  command:
    cmd: "python /var/influxdb/scripts/solar_init_measurements.py"
  args:
    chdir: "/var/influxdb/scripts"

- name: execute solar_init_measurements.py script Solar
  command:
    cmd: "python /var/influxdb/scripts/rs485_init_measurements.py"
  args:
    chdir: "/var/influxdb/scripts"