---
- name: install pip packages
  pip:
    name: [ "requests", "influxdb" ]

- name: Ensure solar directory exists
  file:
    path: "/var/solar/"
    state: directory
    owner: pi
    group: pi

- name: Ensure solar directory exists
  file:
    path: "/var/log/solar"
    state: directory
    owner: pi
    group: pi

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: "/var/solar/{{ item }}"
    owner: pi
    group: pi
    mode: 0775
  with_items:
    - config.ini
    - ginlong-listen.py
    
- name: ginlong-listen.service with owner and permissions
  copy:
    src: ginlong-listen.service
    dest: /lib/systemd/system/ginlong-listen.service
    mode: '0644'

#- name: Make sure ginlong.listen is running
#  systemd:
#    enabled: yes
#    state: started
#    daemon_reload: true
#    name: ginlong.listen