---
- name: install pip packages
  pip:
    name: [ "requests", "influxdb" ]

- name: Ensure solar directory exists
  file:
    path: "/var/solar/"
    state: directory
    owner: pi
    group: pi

- name: Ensure solar directory exists
  file:
    path: "/var/log/solar"
    state: directory
    owner: pi
    group: pi

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: "/var/solar/{{ item }}"
    owner: pi
    group: pi
    mode: 0775
  with_items:
    - solar_config.ini
    - solar-listen.py
    - rs485_config.ini
    - solar_rs485_eth.py
    - rs485eth.py

- name: solar-listen.service with owner and permissions
  copy:
    src: solar-listen.service
    dest: /lib/systemd/system/solar-listen.service
    mode: '0644'

- name: Make sure solar.listen is running
  systemd:
    enabled: yes
    state: started
    daemon_reload: true
    name: solar-listen

- name: restart service solar-listen"
  cron:
    name: "restart service solar-listen"
    minute: "0,15,30,45"
    job: "service solar-listen restart"
    user: root

- name: include create continuous queries 
  include_tasks: init_measurements.yml 
