---
- name: Copy p1.py with owner and permissions
  copy:
    src: p1.py
    dest: /home/pi/p1.py
    mode: '0766'

- name: Copy p1.service with owner and permissions
  copy:
    src: p1.service
    dest: /lib/systemd/system/p1.service
    mode: '0644'

- name: install pip packages
  pip:
    name: [ "pyserial", "crcmod", "influxdb" ]

- name: Make sure p1 is running
  systemd:
    enabled: yes
    state: started
    name: p1