---
- name: install pip packages
  pip:
    name: [ "pyserial", "crcmod", "influxdb" ]


- name: Ensure p1 directory exists
  file:
    path: "/var/p1/"
    state: directory
    owner: pi
    group: pi

- name: Ensure p1 directory exists
  file:
    path: "/var/log/p1"
    state: directory
    owner: pi
    group: pi

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: "/var/p1/{{ item }}"
    owner: pi
    group: pi
    mode: 0775
  with_items:
    - p1_config.ini
    - p1-logger.py

- name: Copy p1.service with owner and permissions
  copy:
    src: p1-logger.service
    dest: /lib/systemd/system/p1-logger.service
    mode: '0644'

- name: Make sure p1-logger is running
  systemd:
    enabled: yes
    state: started
    name: p1-logger

- name: restart service p1-logger"
  cron:
    name: "restart service p1-logger"
    minute: "*/15"
    job: "/usr/sbin/service p1-logger restart"
    user: root

- name: include create continuous queries 
  include_tasks: init_measurements.yml 